### ISSUE TITLE
Weights when converting correlations to Stokes parameters.

### ISSUE THREAD

**Issue by LeoVergaraS** [ratt-ru/codex-africanus#306]
I am converting the correlations to Stokes parameters using the Convert function, which does not give me any problems, however when I try to convert the correlation weights to Stokes parameter weights, I realize that one of the Stokes parameter weights is set to 0 (V for linear correlations and U for circular correlations) because the weights are a real number. Could you explain how to convert the weights?

Sorry for my English, it is not my native language so I am using a translator.

**Comment by landmanbester** [comment]
Assuming you are working with corrected data (so that there are no gains to consider) you can work out the Stokes weights by consider the linear transformation that maps correlations to Stokes. For linear feeds, supposing you have weights W00, W01, W10, and W11 for the correlations, the weights for the stokes parameters work out to be

WI = W00 + W11
WQ = W00 + W11
WU = W01 + W10
WV = W01 + W10

Keep in mind that the presence of gains with non-unity amplitudes (such as bandpass) complicate these expressions but if you have propagated them correctly while forming corrected data the above holds for the on diagonal part of the "Mueller" weights
